sudo: required
services:
  - docker

before_install:
  - docker build -t stevenpy/frontend -f Dockerfile.dev .

script:
  - docker run stevenpy/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: frontend
  environment: "Docker-env"
  bucket_name: "name_of_bucket"
  bucket_path: "frontend"
  on:
    branch: master
